spring:
  application:
    name: nacos-client2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 这里面的nacos地址是你自己的nacos-server的地址
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
server:
  port: 8082